package com.pilates.booking.domain;

import static com.pilates.booking.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ClassSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSessionAllPropertiesEquals(ClassSession expected, ClassSession actual) {
        assertClassSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertClassSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSessionAllUpdatablePropertiesEquals(ClassSession expected, ClassSession actual) {
        assertClassSessionUpdatableFieldsEquals(expected, actual);
        assertClassSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSessionAutoGeneratedPropertiesEquals(ClassSession expected, ClassSession actual) {
        assertThat(actual)
            .as("Verify ClassSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSessionUpdatableFieldsEquals(ClassSession expected, ClassSession actual) {
        assertThat(actual)
            .as("Verify ClassSession relevant properties")
            .satisfies(a -> assertThat(a.getCoachName()).as("check coachName").isEqualTo(expected.getCoachName()))
            .satisfies(a ->
                assertThat(a.getStartAt()).as("check startAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getStartAt())
            )
            .satisfies(a ->
                assertThat(a.getEndAt()).as("check endAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getEndAt())
            )
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSessionUpdatableRelationshipsEquals(ClassSession expected, ClassSession actual) {
        assertThat(actual)
            .as("Verify ClassSession relationships")
            .satisfies(a -> assertThat(a.getStudio()).as("check studio").isEqualTo(expected.getStudio()))
            .satisfies(a -> assertThat(a.getClassType()).as("check classType").isEqualTo(expected.getClassType()));
    }
}
