package com.pilates.booking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PackAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAllPropertiesEquals(Pack expected, Pack actual) {
        assertPackAutoGeneratedPropertiesEquals(expected, actual);
        assertPackAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAllUpdatablePropertiesEquals(Pack expected, Pack actual) {
        assertPackUpdatableFieldsEquals(expected, actual);
        assertPackUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAutoGeneratedPropertiesEquals(Pack expected, Pack actual) {
        assertThat(actual)
            .as("Verify Pack auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackUpdatableFieldsEquals(Pack expected, Pack actual) {
        assertThat(actual)
            .as("Verify Pack relevant properties")
            .satisfies(a -> assertThat(a.getPackName()).as("check packName").isEqualTo(expected.getPackName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getBillingPeriod()).as("check billingPeriod").isEqualTo(expected.getBillingPeriod()))
            .satisfies(a -> assertThat(a.getCredits()).as("check credits").isEqualTo(expected.getCredits()))
            .satisfies(a -> assertThat(a.getValidityDays()).as("check validityDays").isEqualTo(expected.getValidityDays()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackUpdatableRelationshipsEquals(Pack expected, Pack actual) {
        // empty method
    }
}
