package com.pilates.booking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeriodSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodSubscriptionAllPropertiesEquals(PeriodSubscription expected, PeriodSubscription actual) {
        assertPeriodSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPeriodSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodSubscriptionAllUpdatablePropertiesEquals(PeriodSubscription expected, PeriodSubscription actual) {
        assertPeriodSubscriptionUpdatableFieldsEquals(expected, actual);
        assertPeriodSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodSubscriptionAutoGeneratedPropertiesEquals(PeriodSubscription expected, PeriodSubscription actual) {
        assertThat(actual)
            .as("Verify PeriodSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodSubscriptionUpdatableFieldsEquals(PeriodSubscription expected, PeriodSubscription actual) {
        assertThat(actual)
            .as("Verify PeriodSubscription relevant properties")
            .satisfies(a -> assertThat(a.getSubscriptionName()).as("check subscriptionName").isEqualTo(expected.getSubscriptionName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getBillingPeriod()).as("check billingPeriod").isEqualTo(expected.getBillingPeriod()))
            .satisfies(a -> assertThat(a.getCreditsPerPeriod()).as("check creditsPerPeriod").isEqualTo(expected.getCreditsPerPeriod()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodSubscriptionUpdatableRelationshipsEquals(PeriodSubscription expected, PeriodSubscription actual) {
        // empty method
    }
}
