package com.pilates.booking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudioAllPropertiesEquals(Studio expected, Studio actual) {
        assertStudioAutoGeneratedPropertiesEquals(expected, actual);
        assertStudioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudioAllUpdatablePropertiesEquals(Studio expected, Studio actual) {
        assertStudioUpdatableFieldsEquals(expected, actual);
        assertStudioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudioAutoGeneratedPropertiesEquals(Studio expected, Studio actual) {
        assertThat(actual)
            .as("Verify Studio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudioUpdatableFieldsEquals(Studio expected, Studio actual) {
        assertThat(actual)
            .as("Verify Studio relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudioUpdatableRelationshipsEquals(Studio expected, Studio actual) {
        // empty method
    }
}
